# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: oapi
generate:
  std-http-server: true
  models: true
  strict-server: true
  embedded-spec: true
output: internal/oapi/gen.go
